/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package defensesystem;



/**
 *
 * @author BIHAN
 */
public class MainController extends javax.swing.JFrame implements Observable{
    
   
    private Observer observer;
    public MainController(Observer observer) {
        this.observer = observer;
        initComponents();
        setVisible(true);
        setTitle("Main Controller");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        selectDefences = new javax.swing.JComboBox<>();
        btnCollectInfo = new javax.swing.JButton();
        lblClearArea = new javax.swing.JLabel();
        togleBtnAreaClear = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        sendMassageTxtArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        positionTxtArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        soldierLbl = new javax.swing.JLabel();
        fuelLbl = new javax.swing.JLabel();
        ammoLbl = new javax.swing.JLabel();
        strengthSlider = new javax.swing.JSlider();
        jScrollPane2 = new javax.swing.JScrollPane();
        allMassageTxtArea = new javax.swing.JTextArea();
        TogleBtnPrivate = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        sendButtonMainController = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        selectDefences.setBackground(new java.awt.Color(0, 0, 255));
        selectDefences.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        selectDefences.setForeground(new java.awt.Color(255, 255, 255));
        selectDefences.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Defence", "Helicopter", "Tank", "Submarine" }));
        selectDefences.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectDefencesActionPerformed(evt);
            }
        });

        btnCollectInfo.setBackground(new java.awt.Color(51, 102, 255));
        btnCollectInfo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCollectInfo.setForeground(new java.awt.Color(255, 255, 255));
        btnCollectInfo.setText("Collect Information");
        btnCollectInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCollectInfoActionPerformed(evt);
            }
        });

        lblClearArea.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblClearArea.setForeground(new java.awt.Color(255, 255, 255));
        lblClearArea.setText("Area Clear");

        togleBtnAreaClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togleBtnAreaClearActionPerformed(evt);
            }
        });

        sendMassageTxtArea.setColumns(20);
        sendMassageTxtArea.setRows(5);
        sendMassageTxtArea.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                sendMassageTxtAreaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(sendMassageTxtArea);

        positionTxtArea.setColumns(20);
        positionTxtArea.setRows(5);
        positionTxtArea.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                positionTxtAreaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane3.setViewportView(positionTxtArea);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Soldier Count");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fuel Amount");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ammo Amount");

        soldierLbl.setForeground(new java.awt.Color(255, 255, 255));
        soldierLbl.setText("100");

        fuelLbl.setForeground(new java.awt.Color(255, 255, 255));
        fuelLbl.setText("100");

        ammoLbl.setForeground(new java.awt.Color(255, 255, 255));
        ammoLbl.setText("100");

        strengthSlider.setBackground(new java.awt.Color(204, 204, 255));
        strengthSlider.setMajorTickSpacing(20);
        strengthSlider.setMinorTickSpacing(10);
        strengthSlider.setPaintLabels(true);
        strengthSlider.setPaintTicks(true);
        strengthSlider.setValue(0);
        strengthSlider.setOpaque(true);
        strengthSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                strengthSliderStateChanged(evt);
            }
        });

        allMassageTxtArea.setColumns(20);
        allMassageTxtArea.setRows(5);
        jScrollPane2.setViewportView(allMassageTxtArea);

        TogleBtnPrivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TogleBtnPrivateActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Send Private");

        sendButtonMainController.setBackground(new java.awt.Color(0, 0, 255));
        sendButtonMainController.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sendButtonMainController.setForeground(new java.awt.Color(255, 255, 255));
        sendButtonMainController.setText("Send");
        sendButtonMainController.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonMainControllerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(selectDefences, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCollectInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(togleBtnAreaClear, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblClearArea, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ammoLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(soldierLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fuelLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(strengthSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(TogleBtnPrivate, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(sendButtonMainController)
                                        .addGap(15, 15, 15))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap())))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblClearArea, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(togleBtnAreaClear, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(selectDefences, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCollectInfo))))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(soldierLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fuelLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ammoLbl))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(8, 8, 8)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(strengthSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(TogleBtnPrivate, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sendButtonMainController)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectDefencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectDefencesActionPerformed
       
    }//GEN-LAST:event_selectDefencesActionPerformed

    private void TogleBtnPrivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TogleBtnPrivateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TogleBtnPrivateActionPerformed

    private void btnCollectInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCollectInfoActionPerformed
        String selectedItem = (String) selectDefences.getSelectedItem();
            
        switch(selectedItem){
            case "Helicopter" -> { 
                soldierLbl.setText(soldierCountH+"");
                ammoLbl.setText(ammoCountH+"");
                fuelLbl.setText(fuelCountH+"");
            }
            case "Tank" -> { 
                soldierLbl.setText(soldierCountT+"");
                ammoLbl.setText(ammoCountT+"");
                fuelLbl.setText(fuelCountT+"");
            }
            case "Submarine" -> { 
                soldierLbl.setText(soldierCountS+"");
                ammoLbl.setText(ammoCountS+"");
                fuelLbl.setText(fuelCountS+"");
            }
        }
  
    }//GEN-LAST:event_btnCollectInfoActionPerformed

    private void togleBtnAreaClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togleBtnAreaClearActionPerformed
        if (togleBtnAreaClear.isSelected()) {
            this.areaClear = "Area Clear";
            observer.setAreaClear(areaClear);
        }else{
            this.areaClear = "Area Not Clear";
            observer.setAreaClear(areaClear);
        }
    }//GEN-LAST:event_togleBtnAreaClearActionPerformed

    private void strengthSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_strengthSliderStateChanged
               
           String selectedItem = (String) selectDefences.getSelectedItem();
        this.strength = strengthSlider.getValue();
        
         if (TogleBtnPrivate.isSelected()) {
            
            switch (selectedItem) {
                case "Helicopter" -> observer.setStrngthIntHelicopter(strength);
                case "Submarine" -> observer.setStrngthIntSubmarine(strength);
                case "Tank" -> observer.setStrngthIntTank(strength);
                
            }
        }else{
           observer.setStrengthString(strength);
        }
    }//GEN-LAST:event_strengthSliderStateChanged

    private void sendButtonMainControllerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonMainControllerActionPerformed
         String selectedItem = (String) selectDefences.getSelectedItem();
        this.strength = strengthSlider.getValue();
        this.privateMassage = "Your Strength is "+strength;
        String message = sendMassageTxtArea.getText();
         if (TogleBtnPrivate.isSelected()) {
            
            switch (selectedItem) {
                case "Helicopter" -> observer.setStrngthHelicopter(privateMassage,"Controller",message);
                case "Submarine" -> observer.setStrngthSubmarine(privateMassage,"Controller",message);
                case "Tank" -> observer.setStrngthTank(privateMassage,"Controller",message);
                
            }
        }else{
           observer.setStrngthAll(privateMassage,"Controller",message);
        }
    }//GEN-LAST:event_sendButtonMainControllerActionPerformed

    private void positionTxtAreaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_positionTxtAreaAncestorAdded
        
    }//GEN-LAST:event_positionTxtAreaAncestorAdded

    private void sendMassageTxtAreaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_sendMassageTxtAreaAncestorAdded
            
        
    }//GEN-LAST:event_sendMassageTxtAreaAncestorAdded

    @Override
    public void updateHelicopterMainController(int soldierCount,int ammoCount,int fuelCount,String massage){
       this.soldierCountH=soldierCount;
        this.ammoCountH = ammoCount;
        this.massageH = massage;
        this.fuelCountH =fuelCount;
    }
    @Override
    public void updateTankMainController(int soldierCount,int ammoCount,int fuelCount,String massage){
        this.soldierCountT=soldierCount;
        this.ammoCountT = ammoCount;
        this.massageT = massage;
        this.fuelCountT =fuelCount;
    }
    @Override
    public void updateSubmarineMainController(int soldierCount,int ammoCount,int fuelCount,String massage){
        this.soldierCountS=soldierCount;
        this.ammoCountS = ammoCount;
        this.massageS = massage;
        this.fuelCountS =fuelCount;
    }
    
     @Override
    public void updateMassageInMain(String strengthMassage,String defenceName){
             if ("Tank".equals(defenceName)) {
              allMassageTxtArea.setText(allMassageTxtArea.getText() + "Me : " + strengthMassage +"\n");
          } else {
              allMassageTxtArea.setText(allMassageTxtArea.getText() +  defenceName +" : " + strengthMassage +"\n");
          }
    }
    
    @Override
    public void updatePosition(String position,String positionName){
        positionTxtArea.setText(positionTxtArea.getText() +  positionName +" : " + position +"\n");
    }
    @Override
    public  void updateButton(int stengthStr){}
    private int soldierCountH;private int ammoCountH;private int fuelCountH;private String massageH;private String areaClear;
    private int soldierCountS;private int ammoCountS;private int fuelCountS;private String massageS;
    private int soldierCountT;private int ammoCountT;private int fuelCountT;private String massageT;
    
    private int strength;
    private String privateMassage;
    private String broadCastMassage;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton TogleBtnPrivate;
    private javax.swing.JTextArea allMassageTxtArea;
    private javax.swing.JLabel ammoLbl;
    private javax.swing.JButton btnCollectInfo;
    private javax.swing.JLabel fuelLbl;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblClearArea;
    private javax.swing.JTextArea positionTxtArea;
    private javax.swing.JComboBox<String> selectDefences;
    private javax.swing.JButton sendButtonMainController;
    private javax.swing.JTextArea sendMassageTxtArea;
    private javax.swing.JLabel soldierLbl;
    private javax.swing.JSlider strengthSlider;
    private javax.swing.JToggleButton togleBtnAreaClear;
    // End of variables declaration//GEN-END:variables

@Override
    public void update(String areaClear){}
    @Override
    public void updateStrengthMassageHelicopter(String strengthMassage,String defenceName,String message){}
    @Override
    public void updateStrengthMassageTank(String strengthMassage,String defenceName,String message){}
    @Override
    public void updateStrengthMassageSubmarine(String strengthMassage,String defenceName,String message){}
    @Override
    public void updateStrengthMassageAll(String strengthMassage,String defenceName,String message){}
     @Override
    public void updateStrengthIntTank(int strengthMassage){}
    @Override
    public void updateStrengthIntSubmarine(int strengthMassage){}
    @Override
    public void updateStrengthIntHelicopter(int strengthMassage){}
    
}
