/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package defensesystem;

import javax.swing.JOptionPane;

/**
 *
 * @author BIHAN
 */
public class Tank extends javax.swing.JFrame implements Observable {

    /**
     * Creates new form Helicopter
     */
   private final Observer observer;
    public Tank(Observer observer) {
        this.observer = observer;
        initComponents();
        setVisible(true);
        setTitle("Tank");
        
         btnShoot.setEnabled(false);
         btnMissileOperation.setEnabled(false);
         btnReaderOperation.setEnabled(false);
         btnRotateShooting.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        slider = new javax.swing.JSlider();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        togglePosition = new javax.swing.JToggleButton();
        btnShoot = new javax.swing.JButton();
        lblPosition = new javax.swing.JLabel();
        btnMissileOperation = new javax.swing.JButton();
        btnReaderOperation = new javax.swing.JButton();
        lblSoldierCount = new javax.swing.JLabel();
        btnRotateShooting = new javax.swing.JButton();
        lblAmmoCount = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        spinnerSoldier = new javax.swing.JSpinner();
        spinnerAmmo = new javax.swing.JSpinner();
        lblAddAreaCleared = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        btnSend.setBackground(new java.awt.Color(51, 51, 255));
        btnSend.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSend.setForeground(new java.awt.Color(255, 255, 255));
        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        slider.setBackground(new java.awt.Color(204, 204, 255));
        slider.setMajorTickSpacing(20);
        slider.setMinorTickSpacing(10);
        slider.setOrientation(javax.swing.JSlider.VERTICAL);
        slider.setPaintLabels(true);
        slider.setPaintTicks(true);
        slider.setOpaque(true);
        slider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderStateChanged(evt);
            }
        });

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        togglePosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togglePositionActionPerformed(evt);
            }
        });

        btnShoot.setBackground(new java.awt.Color(51, 51, 255));
        btnShoot.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnShoot.setForeground(new java.awt.Color(255, 255, 255));
        btnShoot.setText("Shoot");
        btnShoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShootActionPerformed(evt);
            }
        });

        lblPosition.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPosition.setForeground(new java.awt.Color(255, 255, 255));
        lblPosition.setText("Position");

        btnMissileOperation.setBackground(new java.awt.Color(51, 51, 255));
        btnMissileOperation.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMissileOperation.setForeground(new java.awt.Color(255, 255, 255));
        btnMissileOperation.setText("Missile Operation");
        btnMissileOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMissileOperationActionPerformed(evt);
            }
        });

        btnReaderOperation.setBackground(new java.awt.Color(51, 51, 255));
        btnReaderOperation.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReaderOperation.setForeground(new java.awt.Color(255, 255, 255));
        btnReaderOperation.setText("Reader Operation");
        btnReaderOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReaderOperationActionPerformed(evt);
            }
        });

        lblSoldierCount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSoldierCount.setForeground(new java.awt.Color(255, 255, 255));
        lblSoldierCount.setText("Soldier Count");

        btnRotateShooting.setBackground(new java.awt.Color(51, 51, 255));
        btnRotateShooting.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRotateShooting.setForeground(new java.awt.Color(255, 255, 255));
        btnRotateShooting.setText("Rotate Shooting");
        btnRotateShooting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRotateShootingActionPerformed(evt);
            }
        });

        lblAmmoCount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAmmoCount.setForeground(new java.awt.Color(255, 255, 255));
        lblAmmoCount.setText("Ammo Count");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fuel Count");

        spinnerSoldier.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerSoldierStateChanged(evt);
            }
        });

        spinnerAmmo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerAmmoStateChanged(evt);
            }
        });

        lblAddAreaCleared.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAddAreaCleared.setForeground(new java.awt.Color(255, 255, 255));
        lblAddAreaCleared.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddAreaCleared.setText("Area Not Cleared");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnShoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnReaderOperation))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnMissileOperation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRotateShooting, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(28, 28, 28)
                                            .addComponent(togglePosition, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(lblPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addGap(33, 33, 33)
                                            .addComponent(lblAmmoCount, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(lblSoldierCount, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(lblAddAreaCleared, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(spinnerSoldier, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinnerAmmo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblAddAreaCleared, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnShoot)
                                    .addComponent(btnMissileOperation)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(lblAmmoCount)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReaderOperation))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(spinnerAmmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(spinnerSoldier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblSoldierCount)
                                    .addComponent(jLabel1))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(47, 47, 47)
                                                .addComponent(btnRotateShooting))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(52, 52, 52)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(togglePosition, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblPosition))))
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnSend)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(slider, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReaderOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReaderOperationActionPerformed
        
    }//GEN-LAST:event_btnReaderOperationActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
       if (txt.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"You can not send null message........");
        }else{
            observer.setMessageToMainController(txt.getText(),"Tank");
        }
    }//GEN-LAST:event_btnSendActionPerformed

    private void spinnerSoldierStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerSoldierStateChanged
       this.soldierCount = (int)spinnerSoldier.getValue();
      observer.setTankValues(soldierCount,ammoCount , fuelCount, massage);
    }//GEN-LAST:event_spinnerSoldierStateChanged

    private void spinnerAmmoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerAmmoStateChanged
       this.ammoCount = (int)spinnerAmmo.getValue();
       observer.setTankValues(soldierCount,ammoCount , fuelCount, massage);
    }//GEN-LAST:event_spinnerAmmoStateChanged

    private void sliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderStateChanged
         this.fuelCount = slider.getValue();
         observer.setTankValues(soldierCount,ammoCount , fuelCount, massage);
    }//GEN-LAST:event_sliderStateChanged

    private void btnShootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShootActionPerformed
       
    }//GEN-LAST:event_btnShootActionPerformed

    private void btnMissileOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMissileOperationActionPerformed
        
    }//GEN-LAST:event_btnMissileOperationActionPerformed

    private void btnRotateShootingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRotateShootingActionPerformed
       
    }//GEN-LAST:event_btnRotateShootingActionPerformed

    private void togglePositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togglePositionActionPerformed
       if (togglePosition.isSelected()) {
                this.position = "Helicopter is possition now";
                observer.setPosition(position,"Tank");
                }else{
                    this.position = "Area Not Clear";
                    observer.setPosition(position,"Tank");
            }
    }//GEN-LAST:event_togglePositionActionPerformed

     @Override
   public void update(String areaClear){
         lblAddAreaCleared.setText(areaClear);    
   }
   
   @Override
    public void updateStrengthMassageTank(String strengthMassage,String defenceName,String message){
            txtArea.setText(txtArea.getText() +  defenceName +" : " + strengthMassage +" "+message+"\n");
    }
   
    @Override
    public void updateStrengthMassageAll(String strengthMassage,String defenceName,String message){
        if ("Tank".equals(defenceName)) {
              txtArea.setText(txtArea.getText() + "Me : " + strengthMassage+" "+message +"\n");
          } else {
              txtArea.setText(txtArea.getText() +  defenceName +" : " + strengthMassage+" "+message +"\n");
          }
     }
   @Override
    public  void updateButton(int stengthStr){
        if (togglePosition.isSelected()) {
            if (stengthStr<20) {
                    btnShoot.setEnabled(false);
                     btnMissileOperation.setEnabled(false);
                     btnReaderOperation.setEnabled(false);
                     btnRotateShooting.setEnabled(false);
                }else if (stengthStr>20  && stengthStr<40) {
                     btnShoot.setEnabled(true);
                     btnMissileOperation.setEnabled(false);
                     btnReaderOperation.setEnabled(false);
                     btnRotateShooting.setEnabled(false);
                }else if (stengthStr>=40  && stengthStr<60) {
                     btnShoot.setEnabled(true);
                     btnMissileOperation.setEnabled(true);
                     btnReaderOperation.setEnabled(false);
                     btnRotateShooting.setEnabled(false);
                }else if (stengthStr>60 && stengthStr<80) {
                     btnShoot.setEnabled(true);
                     btnMissileOperation.setEnabled(true);
                     btnReaderOperation.setEnabled(true);
                     btnRotateShooting.setEnabled(false);
                }else if (stengthStr>=80) {
                     btnShoot.setEnabled(true);
                     btnMissileOperation.setEnabled(true);
                     btnReaderOperation.setEnabled(true);
                     btnRotateShooting.setEnabled(true);
            }
        }
    }
    @Override
    public void updateStrengthIntTank(int stengthStr){
        if (togglePosition.isSelected()) {
            if (stengthStr<20) {
                btnShoot.setEnabled(false);
                 btnMissileOperation.setEnabled(false);
                 btnReaderOperation.setEnabled(false);
                 btnRotateShooting.setEnabled(false);
            }else if (stengthStr>20  && stengthStr<40) {
                 btnShoot.setEnabled(true);
                 btnMissileOperation.setEnabled(false);
                 btnReaderOperation.setEnabled(false);
                 btnRotateShooting.setEnabled(false);
            }else if (stengthStr>=40  && stengthStr<60) {
                 btnShoot.setEnabled(true);
                 btnMissileOperation.setEnabled(true);
                 btnReaderOperation.setEnabled(false);
                 btnRotateShooting.setEnabled(false);
            }else if (stengthStr>60 && stengthStr<80) {
                 btnShoot.setEnabled(true);
                 btnMissileOperation.setEnabled(true);
                 btnReaderOperation.setEnabled(true);
                 btnRotateShooting.setEnabled(false);
            }else if (stengthStr>=80) {
                 btnShoot.setEnabled(true);
                 btnMissileOperation.setEnabled(true);
                 btnReaderOperation.setEnabled(true);
                 btnRotateShooting.setEnabled(true);
            }
        }
    }
    
   
    private String position;
    private int soldierCount;
    private int ammoCount;
    private int fuelCount;
    private String massage;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMissileOperation;
    private javax.swing.JButton btnReaderOperation;
    private javax.swing.JButton btnRotateShooting;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnShoot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddAreaCleared;
    private javax.swing.JLabel lblAmmoCount;
    private javax.swing.JLabel lblPosition;
    private javax.swing.JLabel lblSoldierCount;
    private javax.swing.JSlider slider;
    private javax.swing.JSpinner spinnerAmmo;
    private javax.swing.JSpinner spinnerSoldier;
    private javax.swing.JToggleButton togglePosition;
    private javax.swing.JTextField txt;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateHelicopterMainController(int soldierCount,int ammoCount,int fuelCount,String massage){}
    @Override
    public void updateTankMainController(int soldierCount,int ammoCount,int fuelCount,String massage){}
    @Override
    public void updateSubmarineMainController(int soldierCount,int ammoCount,int fuelCount,String massage){}
    @Override
    public void updateStrengthMassageHelicopter(String strengthMassage,String defenceName,String message){}
    @Override
    public void updateStrengthMassageSubmarine(String strengthMassage,String defenceName,String message){}
     @Override
    public void updateMassageInMain(String strengthMassage,String defenceName){}
     @Override
    public void updateStrengthIntHelicopter(int strengthMassage){}
     @Override
    public void updateStrengthIntSubmarine(int strengthMassage){}
    @Override
    public void updatePosition(String position,String positionName){}
  
   
}
